# Generated by Django 3.2.11 on 2022-02-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-time_created']},
        ),
    ]
